# fly.toml file generated for welog on 2023-03-17T15:10:26+09:00

app = "welog"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
processes = []

[env]
  PORT = "3690"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3690
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
